[package]
name = "Ultimate Fishing"
authors = [ "Merlord",]
version = "0.0.10"

[dependencies]
assets = []

[dependencies.mwse]
buildnumber = 3066

[dependencies.mge-xe]
version = ">=0.15.0"

[tools.mwse]
lua-mod = "mer.fishing"

[dependencies.mods."Skills Module"]
mwse-module = "OtherSkills"
url = "https://www.nexusmods.com/morrowind/mods/46034?tab=files"

[dependencies.mods."The Crafting Framework"]
mwse-module = "CraftingFramework"
version = "^1.10.4"
url = "https://www.nexusmods.com/morrowind/mods/51009?tab=files"
